// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCte48zJQse-71qk_QCK0g0pfMNV1DGkfk',
    appId: '1:930109818035:web:ad3bf54a4cc0108f651cc6',
    messagingSenderId: '930109818035',
    projectId: 'yet-app-29290',
    authDomain: 'yet-app-29290.firebaseapp.com',
    storageBucket: 'yet-app-29290.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTFaPlD0E_J2JZrznajY53-lPn9FtO8gs',
    appId: '1:930109818035:android:cd352564d5da176f651cc6',
    messagingSenderId: '930109818035',
    projectId: 'yet-app-29290',
    storageBucket: 'yet-app-29290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLk4hvOmMDzEjbED57JV0H-94Y-bksSzc',
    appId: '1:930109818035:ios:cba91b6fdad828c3651cc6',
    messagingSenderId: '930109818035',
    projectId: 'yet-app-29290',
    storageBucket: 'yet-app-29290.firebasestorage.app',
    iosBundleId: 'com.example.yetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCte48zJQse-71qk_QCK0g0pfMNV1DGkfk',
    appId: '1:930109818035:web:c749a3445f444505651cc6',
    messagingSenderId: '930109818035',
    projectId: 'yet-app-29290',
    authDomain: 'yet-app-29290.firebaseapp.com',
    storageBucket: 'yet-app-29290.firebasestorage.app',
  );
}
